### ISSUE TITLE
issue of uncertainty....

### ISSUE THREAD

**Issue by MichaelTen** [luckyr13/arwiki#5]
is this wiki really decentralized? is there a simple info page about this wiki system? my issue is is that i am having a hard time discerning this. thank you. limitless peace.

**Comment by luckyr13** [comment]
Hello @MichaelTen , this is a great question, I would do my best on this. 

So, how decentralized is our ArWiki?

1. Hosting. Traditional websites host their files in private servers. ArWiki is different because all our content is hosted on the Arweave blockchain, also called, the blockweave. This has a number of effects, but one of these is that all the deployed ArWiki versions are always available. You can take a look at our Changelog to see all our deployed versions here: https://github.com/luckyr13/arwiki/blob/master/CHANGELOG.md
2. Database?. We don't use traditional databases. Instead, we use smartweave contracts. A smartweave contract is hosted in the blockweave, so it's always available from any Arweave gateway. From docs: `SmartWeave is a smart contracting platform built on top of the Arweave network. It allows users and developers to build programs whose execution is trustable and decentralized. One of the unique features of SmartWeave is the process of lazy evaluation, which removes the burden of processing smart contracts from the nodes and moves it to the users.`. https://arwiki.wiki/#/en/smartweave
3. Open Protocol. In a traditional wiki any new user can contribute and publish new content and the content needs to be approved by another special role. New users needs to register in a traditional wiki. In ArWiki anyone with an Arweave wallet can join and publish a new article proposal. This new page is saved as an arweave tx on the arweave blockchain. The page is not immediatly listed, it needs to be reviewed and approved first by a human Moderator. In Arweave you can create open protocols adding tags to your files deployed. So we add a tag with something like `ArWiki-Page` to recognise our pages from the other arweave transactions. If we keep in mind that Arweave is a blockchain for permanent file storage we can realize how powerful is what is going on here! 💪
4. Content Moderation. Our wiki content is managed through a main smartweave contract. All the new proposed pages needs to be approved first by an ArWiki Moderator. This contract is very special and does a lot of things but in resume the contract has all the rules to manage a decentralized community and a community token. The ArWiki contract is a PST contract modified for our needs and is based on the popular Community.XYZ contract. We modified this contract to include our wiki directory. We choose this design because it makes possible to secure the content with our own tokens. Only Moderators can approve new content and Moderators are proposed and removed by the community as needed.

You can take a look to our current main smartcontract here: https://arcode.studio/#/ewepANKEVffP0cm_XKjwTYhSBqaiQrJbVrCcBiWqw-s

This is more or less how it works. You can find more info about how the ArWiki works here: https://arwiki.wiki/#/en/ArWiki
More about PST tokens here: https://arwiki.wiki/#/en/profit-sharing-tokens

Also from docs: 
`As well as storing static files, the permaweb can also host full, decentralized web applications. These applications live independently inside the permaweb, governed purely by their own code, answering to no person or higher authority. Once launched, a permaweb application cannot be modified by anyone and can be used by everyone, permissionlessly. These applications also exist and continue to run with zero maintenance or upkeep costs to the original developer.`
https://arwiki.wiki/#/en/the-permaweb

Let me know if this helps so we can close the issue and please feel free to add any comment to solve further doubts.

Thanks for your nice question 🙏

**Comment by MichaelTen** [comment]
Interesting. Thanks. This helps to clarify some. To edit the wiki, do I need an account? And where can I edit it? Am I able to create my own wiki with this.... like is this project mean to be a set of decentralized wiki farms? Miraheze is an example of a _**quality**_ centralized wiki farm. https://miraheze.org/

thanks for the info and limitless peace.

**Comment by luckyr13** [comment]
hello Michael! Thank you very much for your time and for your questions.

Anyone can propose edits and new articles to our Arweave wiki. We have a Moderation process. ArWiki means Arweave Wiki, so our wiki is only focused to arweave topics.

ArWiki is a platform built with Angular framework and we use the Arweave blockchain as our storage solution and as a database. It's a permaweb app. If you wanna learn more about what is Arweave you are totally invited to read this article: https://arwiki.wiki/#/en/the-permaweb

Anyone can check the ArWiki code and even make a fork to experiment because our code is under MIT license.

You can follow us in our social media if you wanna learn more about our project:

- Discord channel: https://discord.gg/mn8j66r4x3
- Twitter: https://twitter.com/TheArWiki

I hope that you find this information useful!
